apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: foundation-loki
policyDefaults:
  namespace: openshift-gitops          
  remediationAction: enforce          
  consolidateManifests: false
  placement:
    labelSelector:
      matchExpressions:
        - key: platform
          operator: In
          values: ["ocp"]

policies:
  - name: loki-operator-install
    policyType: OperatorPolicy
    manifests:
      - path: subscription.yaml
  - name: loki-stack-config
    manifests:
      - path: lokistack.yaml