apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki-generic
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: loki-generic-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'loki-{{name}}'
    spec:
      project: foundation
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: loki
          targetRevision: 6.x
          helm:
            valueFiles:
              - $values/foundation/operators/loki/generic/values.yaml
        - repoURL: https://github.com/too-common-name/heterogeneous-multicluster-pull.git
          targetRevision: main
          ref: values
      destination:
        name: '{{name}}'
        namespace: loki
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
