apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: loki-generic-placement
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: platform
              operator: In
              values: ["generic"]